name: Run Secret and Dependency Scan

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore: [".github/**"]
  pull_request:
    branches: [master]
    paths-ignore: [".github/**"]

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Dependency Scan
        env:
          PACKAGE: "all"
        run: |
          response=$(curl -sS --location --request POST 'https://ironpipe.com/api/beta/v1/scan/dependencies' \
          --header 'Authorization: ${{ secrets.API_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "package": "'${PACKAGE}'",
              "repoUrl": "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/'${GITHUB_REPOSITORY}'.git",
              "commitID": "'${GITHUB_SHA}'",
              "repoBranchName": "'${{ github.head_ref }}'"
          }');
          echo "$response";
          SCANID=$(echo "$response" | sed -nE 's/.*"scanID":"([^\"]*)",".*/\1/p');
          if [ -z "$SCANID" ]; then exit 1; else export SCANID=$(echo $SCANID); echo "SCANID=$SCANID" >> $GITHUB_ENV; fi;

      - name: Poll Scan Result
        run: |
          echo "Scan ID: ${SCANID}"
          status='IN_PROGRESS'; retry_count=15;
          while [ "$status" == 'IN_PROGRESS' ] && [ $retry_count > 0 ];
            do echo "$status - Waiting for scan $SCANID to complete"; sleep 60; let $((retry_count--));
            response=$(curl -sS --location --request GET "https://ironpipe.com/api/beta/v1/scan/${SCANID}" --header 'Authorization: ${{ secrets.API_TOKEN }}');
            status=$(echo "$response" | sed -nE 's/.*"status":"([^\"]*)",".*/\1/p');
          done; if [ $retry_count == 0 ]; then echo "Timeout. Scan is taking longer than expected"; exit 1; fi; 
          if [ $status != "COMPLETED" ]; then echo "Scan is $status"; exit 1; else echo "Scan has been completed, getting result.."; fi; 
          curl -sS --location --request GET "https://ironpipe.com/api/beta/v1/scan/${SCANID}/issues" --header 'Authorization: ${{ secrets.API_TOKEN }}' > scanresult_sast.json

      - name: Upload Scan Result Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: scanresult_sast.json

      - name: Create GitHub Check
        run: |
          ISSUES_URL="https://ironpipe.com/api/beta/v1/scan/${SCANID}/issues"
          CHECK_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs"
          curl -XPOST $CHECK_URL -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" -H "accept: application/vnd.github.antiope-preview+json" -H "Content-Type: application/json" -d "{\"name\": \"Dependency Scan\", \"head_sha\": \"${GITHUB_REF}\", \"external_id\": \"DependencyScan\", \"details_url\": \"${ISSUES_URL}\", \"status\": \"completed\", \"conclusion\": \"action_required\", \"output\": {\"title\": \"Dependency Scan Result\", \"summary\": \"Issues are stored as workflow artifacts or perform GET ${ISSUES_URL} to retrieve the issues\"}}"

  secret-scan:
    runs-on: ubuntu-latest
      - name: Run Secret Scan
        run: |
          response=$(curl -sS --location --request POST 'https://ironpipe.com/api/beta/v1/scan/secrets' \
          --header 'Authorization: ${{ secrets.API_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "repoUrl": "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/'${GITHUB_REPOSITORY}'.git",
              "repoBranchName": "'${{ github.head_ref }}'"
          }');
          echo "$response";
          SCANID=$(echo "$response" | sed -nE 's/.*"scanID":"([^\"]*)",".*/\1/p');
          if [ -z "$SCANID" ]; then exit 1; else export SCANID=$(echo $SCANID); echo "SCANID=$SCANID" >> $GITHUB_ENV; fi;

      - name: Poll Scan Result
        run: |
          echo "Scan ID: ${SCANID}"
          status='IN_PROGRESS'; retry_count=15;
          while [ "$status" == 'IN_PROGRESS' ] && [ $retry_count > 0 ];
            do echo "$status - Waiting for scan $SCANID to complete"; sleep 60; let $((retry_count--));
            response=$(curl -sS --location --request GET "https://ironpipe.com/api/beta/v1/scan/${SCANID}" --header 'Authorization: ${{ secrets.API_TOKEN }}');
            status=$(echo "$response" | sed -nE 's/.*"status":"([^\"]*)",".*/\1/p');
          done; if [ $retry_count == 0 ]; then echo "Timeout. Scan is taking longer than expected"; exit 1; fi; 
          if [ $status != "COMPLETED" ]; then echo "Scan is $status"; exit 1; else echo "Scan has been completed, getting result.."; fi; 
          curl -sS --location --request GET "https://ironpipe.com/api/beta/v1/scan/${SCANID}/issues" --header 'Authorization: ${{ secrets.API_TOKEN }}' > scanresult_secrets.json

      - name: Upload Scan Result Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: scanresult_secrets.json

      - name: Create GitHub Check
        run: |
          ISSUES_URL="https://ironpipe.com/api/beta/v1/scan/${SCANID}/issues"
          CHECK_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/check-runs"
          curl -XPOST $CHECK_URL -H "Authorization: Token ${{ secrets.GITHUB_TOKEN }}" -H "accept: application/vnd.github.antiope-preview+json" -H "Content-Type: application/json" -d "{\"name\": \"Secret Scan\", \"head_sha\": \"${GITHUB_REF}\", \"external_id\": \"SecretScan\", \"details_url\": \"${ISSUES_URL}\", \"status\": \"completed\", \"conclusion\": \"action_required\", \"output\": {\"title\": \"Secret Scan Result\", \"summary\": \"Issues are stored as workflow artifacts or perform GET ${ISSUES_URL} to retrieve the issues\"}}"
